<a href="https://colab.research.google.com/github/stephenebert/Springboard/blob/main/Mini_Project_Fine_tuning_a_Convolutional_Neural_Network_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

# Part 1

**1. Load the CIFAR-10 dataset after referencing the documentation here.**

In [2]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


**2. Normalize the pixel values so they're all in the range [0, 1].**

In [10]:
print(int(max(x_train.max(), x_test.max())))
print(int(min(x_train.min(), x_test.min())))

255
0


In [11]:
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

In [12]:
print(int(max(x_train.max(), x_test.max())))
print(int(min(x_train.min(), x_test.min())))

1
0


We see that the pixel values are in the range [0, 1]

**3. Apply One Hot Encoding to the train and test labels using the to_categorical function.**

In [29]:
y_train = to_categorical(y_train,10)
y_test = to_categorical(y_test,10)
print(y_train.shape)
print(y_test.shape)

(45000, 10, 10)
(10000, 10, 10)


We see the one hot encoding works for the training and testing labels in CIFAR-10 when we print them. Note that we used Kera's to_categorical() method to convert integers 0, 1, ..., 9 to one-hot encoded vectors. num_classes = 10

In [21]:
print(f'y_train = \n {y_train}')
print('\n')
print(f'y_test = \n {y_test}')

y_train = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


y_test = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


**4. Further split the the training data into training and validation sets using train_test_split. Use only 10% of the data for validation.**

For this, we just use the usual train_test_split from sklearn.model_selection.

In [24]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1, random_state=42, stratify=y_train)

# Part 2

**1. Load VGG16 as a base model. Make sure to exclude the top layer.**

In [30]:
base_model = VGG16(weights = 'imagenet', include_top = False, input_shape = (32, 32, 3))

58889256/58889256 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


**2. Freeze all the layers in the base model. We'll be using these weights as a feature extraction layer to forward to layers that are trainable.**



In [31]:
for layer in base_model.layers:
    layer.trainable = False

The new top layers we'll add next will be the only trainable parts

# Part 3

**1. Using the base model, add a GlobalAveragePooling2D layer, followed by a Dense layer of length 256 with ReLU activation. Finally, add a classification layer with 10 units, corresponding to the 10 CIFAR-10 classes, with softmax activation.**

**2. Create a Keras Model that takes in approproate inputs and outputs.**

# Part 4

**1. Compile your model using an appropriate loss function. Feel free to play around with the optimizer, but a good starting optimizer might be Adam with a learning rate of 0.001.**

**2. Fit your model on the training data. Use the validation data to print the accuracy for each epoch. Try training for 10 epochs. Note, training can take a few hours so go ahead and grab a cup of coffee.**

# Part 5

**1. Use your trained model to calculate the accuracy on the test set. Is the model performance better than random?**

**2. Experiment! See if you can tweak your model to improve performance.**